---

- name: Add a user
  #hosts: "{{ morhost }}"
  hosts: all
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: aditya1
        password: "{{ lookup('cypher','secret=password/10/aapassword') }}"
        state: present
