---
- name: Add a user
  hosts: all
  gather_facts: false
  tasks:
    - name: Add User  
      win_user:
        name: "{{ instance['hostname'] }}"
        password: "@ns1bl3"
        state: present
